name: Build Image

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    branches:
      - "main"
      - "release-[0-9]+.[0-9]+"
  push:
    branches:
      - "main"
      - "release-[0-9]+.[0-9]+"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  envs:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.create-tags.outputs.tags }}

    steps:
      - name: create tags
        id: create-tags
        run: |
          if [[ $GITHUB_EVENT_NAME == 'push' ]]; then
            echo 'TAGS=${{ github.ref_name }}' >> "$GITHUB_OUTPUT"
          else
            {
              echo 'tags<<TAGS'
              echo 'PR-${{ github.event.pull_request.number }}'
              echo '${{ github.event.pull_request.head.sha }}'
              echo 'TAGS'
            } >> "$GITHUB_OUTPUT"
          fi
