name: PR Lifecycle

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  manager-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # wait for the build to succeed so that the manager image is available
      - name: Wait for the image to be available in the registry
        id: wait-for-status
        uses: autotelic/action-wait-for-status-check@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          # IMAGE_REPO: "europe-docker.pkg.dev/kyma-project/dev/telemetry-manager"
          ref: "${{ github.event.pull_request.head.sha }}"
          statusName: "build-image"

  PR-Lifecycle-Success:
    needs: manager-upgrade
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: |
          echo "PR Lifecycle completed successfully"
